AplicacionBdSqlServer/Models/Alumno.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionBdSqlServer.Models
{
    public class Alumno
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
    }
}

AplicacionBdSqlServer/Models/ClasesUpnContext.cs
using AplicacionBdSqlServer.Models.Map;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionBdSqlServer.Models
{
    public interface IClasesUpnContext
    {
         DbSet<Alumno> Alumnos { get; set; }
         DbSet<Profesor> Profesors { get; set; }
         DbSet<Curso> Cursos { get; set; }
        List<Curso> ListaCursos { get; set; }
    }
    public class ClasesUpnContext : DbContext, IClasesUpnContext
    {

        public DbSet<Alumno> Alumnos { get; set; }
        public DbSet<Profesor> Profesors { get; set; }
        public DbSet<Curso> Cursos { get; set; }

        public  List<Curso> ListaCursos { get; set; }
        public ClasesUpnContext(DbContextOptions<ClasesUpnContext> options) : base(options)
        {

        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new AlumnoMap());
            modelBuilder.ApplyConfiguration(new ProfesorMap());
            modelBuilder.ApplyConfiguration(new CursoMap());
        }
    }
}

AplicacionBdSqlServer/Models/Curso.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionBdSqlServer.Models
{
    public class Curso
    {
        public int Id { get; set; }
        public int IdAlumno { get; set; }
        public int IdProfesor { get; set; }
        public string Nombre { get; set; }
        public decimal Nota { get; set; }
        public int Credito { get; set; }

        //Relaciones
        public Alumno Alumnos { get; set; }
        public Profesor Profesores { get; set; }
    }
}

AplicacionBdSqlServer/Models/ErrorViewModel.cs
using System;

namespace AplicacionBdSqlServer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AplicacionBdSqlServer/Models/Map/AlumnoMap.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionBdSqlServer.Models.Map
{
    public class AlumnoMap : IEntityTypeConfiguration<Alumno>
    {
        public void Configure(EntityTypeBuilder<Alumno> builder)
        {
            builder.ToTable("Alumno");
            builder.HasKey(o => o.Id);
        }
    }
}

AplicacionBdSqlServer/Models/Map/CursoMap.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionBdSqlServer.Models.Map
{
    public class CursoMap : IEntityTypeConfiguration<Curso>
    {
        public void Configure(EntityTypeBuilder<Curso> builder)
        {
            builder.ToTable("Curso");
            builder.HasKey(o => o.Id);

            builder.HasOne(o => o.Alumnos).
                WithMany().
                HasForeignKey(o => o.IdAlumno);

            builder.HasOne(o => o.Profesores).
               WithMany().
               HasForeignKey(o => o.IdProfesor);

        }
    }
}

AplicacionBdSqlServer/Models/Map/ProfesorMap.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionBdSqlServer.Models.Map
{
    public class ProfesorMap : IEntityTypeConfiguration<Profesor>
    {
        public void Configure(EntityTypeBuilder<Profesor> builder)
        {
            builder.ToTable("Profesor");
            builder.HasKey(o => o.Id);

        }
    }
}

AplicacionBdSqlServer/Models/Profesor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionBdSqlServer.Models
{
    public class Profesor
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
    }
}

AplicacionBdSqlServer/Controllers/ClasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplicacionBdSqlServer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AplicacionBdSqlServer.Controllers
{
    public class ClasesController : Controller
    {
        private readonly IClasesUpnContext _context;
        public ClasesController(IClasesUpnContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult MiAula()
        {
            ViewBag.Cursos = _context.Cursos.
                Include(o=>o.Alumnos).
                Include(x=>x.Profesores).ToList();
            return View();
        }
        [HttpGet]
        public IActionResult RegistrarA()
        {
            return View(new Alumno());
        }
        [HttpPost]
        public IActionResult RegistrarA(Alumno alumno)
        {
            if (ModelState.IsValid)
            {
                _context.Alumnos.Add(alumno);
              //  _context.SaveChanges();
                return RedirectToAction("RegistrarM",alumno);
            }

            return View(new Alumno());
        }
        [HttpGet]
        public IActionResult RegistrarM(Alumno alumno)
        {
            ViewBag.IdAlumno = alumno.Id;
            ViewBag.Cursos = new List<string>{
                "Matematica","Comunicacion","Programacion"
            };
            ViewBag.Profesores = _context.Profesors.ToList();
            return View(new Curso());
        }
        [HttpPost]
        public IActionResult RegistrarM(Curso curso)
        {
            curso.Nota = 0;
            curso.Credito = 4;
            if (ModelState.IsValid)
            {
                _context.Cursos.Add(curso);
               // _context.SaveChanges();
                return RedirectToAction("MiAula");
            }

            return View(new Curso());
        }
       

        //logued
        //protected User LoggedUser()
        //{
        //    var claim = HttpContext.User.Claims.FirstOrDefault();
        //    var user = _context.Users.Where(o => o.Username == claim.Value).FirstOrDefault();
        //    return user;
        //}
    }
}

AplicacionBdSqlServer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AplicacionBdSqlServer.Models;

namespace AplicacionBdSqlServer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AplicacionBdSqlServer/Views/Clases/MiAula.cshtml
<html>
<head>
    <title>Upn</title>
</head>
<body>
    <h1>Bienvenido</h1>
    <hr />
    <button class="btn btn-success">
        <a href="/clases/registrarA">Registrar Matricula</a>
    </button>
    <div class="container">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Alumno</th>
                    <th>Curso</th>
                    <th>Profesor</th>
                </tr>
            </thead>

            <tbody>
                @{ int i = 0;}
                @foreach (var item in ViewBag.Cursos)
                {
                    i++;
                    <tr>
                        <td>@i</td>
                        <td>@item.Alumnos.Nombre</td>
                        <td>@item.Nombre</td>
                        <td>@item.Profesores.Nombre</td>
                    </tr>
                }

            </tbody>
           
        </table>
    </div>
</body>
</html>

AplicacionBdSqlServer/Views/Clases/RegistrarA.cshtml
@{ var alumno = (Alumno)Model; }

<form action="/clases/registrarA" method="post">
    <label>Por favor Llene sus datos</label>

    <div class="form-group">
        <label>Nombre </label>
        <input class="form-control" placeholder="Nombre Estudiante" name="Nombre" />
    </div>
    <div class="form-group">
        <label>Apellido </label>
        <input class="form-control" placeholder="Apellido Estudiante" name="Apellido" />
    </div>

    <button class="btn btn-primary">Guardar</button>
</form>

AplicacionBdSqlServer/Views/Clases/RegistrarM.cshtml
@{ var curso = (Curso)Model; }

<form action="/clases/registrarm" method="post">

    <input type="hidden" name="IdAlumno" value="@ViewBag.IdAlumno" />
    <div class="form-group">
        <label>Curso</label>
        <select name="Nombre" class="form-control">
            <option value="">-- Selecciona una opcion --</option>
            @foreach (var item in ViewBag.Cursos)
            {
                <option value="@item">@item</option>
            }
        </select>
    </div>

    <div class="form-group">
        <label>Profesor</label>
        <select name="IdProfesor" class="form-control">
            <option value="">-- Selecciona una opcion --</option>
            @foreach (var item in ViewBag.Profesores)
            {
                <option value="@item.Id">@item.Nombre</option>
            }
        </select>
    </div>

    <button class="btn btn-primary">Guardar</button>

</form>

AplicacionBdSqlServer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AplicacionBdSqlServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplicacionBdSqlServer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AplicacionBdSqlServer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clases" asp-action="MiAula">Mi Aula</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AplicacionBdSqlServer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>